const W={long:1,marathon:.9,threshold:.82,interval:.78,easy:.34,strength:.26};
const sample={name:'London Marathon Build',race:'London Marathon',goal:'2:39:59',weeks:12,sessions:[
{week:5,day:'Tue',type:'interval',title:'5 × 1600 m controlled',target:'3:35–3:45/km · 2–3 min recovery',objective:'Improve running economy and speed reserve without excessive fatigue.'},
{week:5,day:'Thu',type:'threshold',title:'3 × 12 min threshold',target:'3:40–3:55/km · 2–3 min recovery',objective:'Raise sustainable aerobic power for marathon performance.'},
{week:5,day:'Sun',type:'long',title:'30–32 km with 2 × 5 km at marathon pace',target:'Easy 4:35–5:00/km · MP 3:47/km',objective:'Build marathon-specific durability and practise holding goal pace late.'},
{week:6,day:'Tue',type:'interval',title:'10 × 600 m',target:'3:20–3:28/km · 90s–2 min recovery',objective:'Sharpen speed and economy.'},
{week:6,day:'Thu',type:'threshold',title:'2 × 20 min threshold',target:'3:40–3:55/km · 3 min recovery',objective:'Extend threshold durability.'},
{week:6,day:'Sun',type:'long',title:'30–32 km with final 8 km steady to MP',target:'Progress 4:00/km → 3:47/km',objective:'Finish strongly under fatigue without forcing the early kilometres.'},
{week:7,day:'Thu',type:'marathon',title:'3 × 5 km at marathon pace',target:'3:47/km · 3–4 min recovery',objective:'Increase confidence and economy at goal marathon pace.'},
{week:7,day:'Sun',type:'long',title:'32 km with last 10 km at marathon pace',target:'Final 10 km at 3:47/km',objective:'Headline marathon-specific long run.'},
{week:8,day:'Sun',type:'long',title:'22–24 km easy',target:'Genuine recovery · no hard finish',objective:'Absorb the peak block and reduce accumulated fatigue.'},
{week:9,day:'Thu',type:'marathon',title:'2 × 6 km at marathon pace',target:'3:47/km · 3 min recovery',objective:'Reinforce race-specific efficiency.'},
{week:9,day:'Sun',type:'long',title:'28–30 km with 10–12 km at marathon pace',target:'MP block at 3:47/km',objective:'Specific but controlled marathon preparation.'}]};
let plan=JSON.parse(localStorage.getItem('build.plan')||'null')||sample;let A=JSON.parse(localStorage.getItem('build.assessments')||'{}');let state={screen:'home',week:5,selected:null};
const key=s=>`${s.week}-${s.day}-${s.title}`;const assess=s=>A[key(s)];const save=()=>{localStorage.setItem('build.plan',JSON.stringify(plan));localStorage.setItem('build.assessments',JSON.stringify(A))};
function metrics(){let total=0,earned=0,n=0,count=0;plan.sessions.filter(s=>s.week<=state.week).forEach(s=>{let w=W[s.type]??.4;total+=w;count++;if(assess(s)){earned+=w*assess(s).score/100;n++}});let progress=total?Math.round(earned/total*100):0,coverage=count?n/count:0;let recent=plan.sessions.filter(s=>s.week>=state.week-2&&s.week<=state.week&&assess(s)).map(s=>assess(s).score);let avg=recent.length?recent.reduce((a,b)=>a+b,0)/recent.length:progress;let forecast=coverage<.25?null:Math.round(progress*.45+avg*.55);return{progress,n,count,forecast,confidence:coverage>.65?'High':coverage>.4?'Medium':'Low'}}
const label=t=>({long:'Long run',marathon:'Marathon pace',threshold:'Threshold',interval:'Intervals',easy:'Easy',strength:'Strength'})[t]||'Session';const icon=t=>({long:'L',marathon:'M',threshold:'T',interval:'I',easy:'E',strength:'S'})[t]||'•';
function row(s){let a=assess(s);return `<div class="session" data-session="${encodeURIComponent(key(s))}"><div class="icon">${icon(s.type)}</div><div class="session-main"><div class="title">${s.day} · ${s.title}</div><div class="sub">${s.target}</div></div><span class="badge">${a?a.score:label(s.type)}</span></div>`}
function home(){let m=metrics(),ss=plan.sessions.filter(s=>s.week===state.week);return `<section class="hero"><div class="eyebrow">Today’s Build · Week ${state.week}</div><h1>Make the next session count.</h1><div class="goal muted">${plan.race} · <b>${plan.goal}</b></div></section><div class="grid"><div class="card metric"><div class="label">BUILD PROGRESS</div><div class="value">${m.progress}%</div><div class="good">${m.n}/${m.count} assessed</div></div><div class="card metric"><div class="label">BUILD FORECAST</div><div class="value">${m.forecast??'—'}</div><div class="good">${m.forecast==null?'Building signal':m.forecast>=85?'On track':m.forecast>=70?'Within reach':'Needs attention'}</div></div></div><div class="section"><h2>This week</h2><button data-nav="plan">View plan</button></div><div class="card">${ss.length?ss.map(row).join(''):'No sessions loaded for this week.'}</div><div class="section"><h2>Coaching insight</h2></div><div class="card"><div class="eyebrow">What matters now</div><p>Key sessions carry more weight than easy mileage. Protect the long run and quality days rather than chasing completion for its own sake.</p></div>`}
function planView(){let ss=plan.sessions.filter(s=>s.week===state.week);return `<section class="hero"><div class="eyebrow">The Plan</div><h1>${plan.name}</h1><p class="muted">The plan is the source of truth. BUILD interprets how completed training contributes to it.</p></section><div class="week-strip">${Array.from({length:plan.weeks},(_,i)=>`<button class="week ${state.week===i+1?'active':''}" data-week="${i+1}">W${i+1}</button>`).join('')}</div><div class="section"><h2>Week ${state.week}</h2><button id="import">Import JSON</button></div><div class="card">${ss.length?ss.map(row).join(''):'No sessions stored for this week.'}</div>`}
function progress(){let m=metrics();let assessed=plan.sessions.filter(assess);return `<section class="hero"><div class="eyebrow">Build Progress</div><h1>${m.progress}% of the work is landing.</h1><p class="muted">Not every run matters equally. Marathon-specific sessions have more influence.</p></section><div class="card"><h2>Progress</h2><br><div class="track"><div class="fill" style="width:${m.progress}%"></div></div><p class="muted">${m.n} sessions assessed · Goal confidence ${m.confidence}</p></div><div class="section"><h2>Assessment history</h2></div><div class="card">${assessed.length?assessed.slice().reverse().map(row).join(''):'No assessed sessions yet.'}</div>`}
function settings(){return `<section class="hero"><div class="eyebrow">Settings</div><h1>Keep the app simple.</h1></section><div class="card"><p><b>Activity source</b><br><span class="muted">Strava · demo mode</span></p><p><b>Plan source</b><br><span class="muted">Imported JSON / sample plan</span></p><p><b>Goal</b><br><span class="muted">${plan.race} · ${plan.goal}</span></p><button class="secondary" id="reset">Reset demo data</button></div>`}
function sheet(s){return `<div class="sheet" id="backdrop"><div class="panel"><div class="eyebrow">${label(s.type)} · Week ${s.week}</div><h1>${s.title}</h1><div class="detail"><b>Planned target</b><br>${s.target}</div><div class="detail"><b>Why it matters</b><br>${s.objective}</div><div class="detail"><b>Impact rating</b><br>${Math.round((W[s.type]??.4)*100)} / 100</div><div class="detail"><b>How did it go?</b><div class="scores">${[[100,'Nailed it'],[82,'Mostly'],[55,'Modified'],[20,'Missed']].map(x=>`<button class="score" data-score="${x[0]}">${x[1]}</button>`).join('')}</div></div><button class="secondary" id="close">Close</button></div></div>`}
function render(){let body=state.screen==='plan'?planView():state.screen==='progress'?progress():state.screen==='settings'?settings():home();document.getElementById('app').innerHTML=`<header class="topbar"><div class="brandrow"><div class="brand">BUILD</div><div class="sync"><span class="dot"></span>Strava demo connected</div></div></header><main>${body}</main><nav class="bottom">${[['home','⌂','Today'],['plan','▦','Plan'],['progress','◔','Progress'],['settings','⚙','Settings']].map(x=>`<button class="nav ${state.screen===x[0]?'active':''}" data-nav="${x[0]}"><span>${x[1]}</span>${x[2]}</button>`).join('')}</nav>${state.selected?sheet(state.selected):''}`;bind()}
function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{state.screen=b.dataset.nav;render()});document.querySelectorAll('[data-week]').forEach(b=>b.onclick=()=>{state.week=+b.dataset.week;render()});document.querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>{let k=decodeURIComponent(b.dataset.session);state.selected=plan.sessions.find(s=>key(s)===k);render()});document.querySelectorAll('[data-score]').forEach(b=>b.onclick=()=>{A[key(state.selected)]={score:+b.dataset.score,at:new Date().toISOString()};save();state.selected=null;render()});let c=document.getElementById('close');if(c)c.onclick=()=>{state.selected=null;render()};let i=document.getElementById('import');if(i)i.onclick=()=>document.getElementById('planFileInput').click();let r=document.getElementById('reset');if(r)r.onclick=()=>{localStorage.clear();plan=sample;A={};state.week=5;render()}}
document.getElementById('planFileInput').addEventListener('change',async e=>{let f=e.target.files[0];if(!f)return;try{let p=JSON.parse(await f.text());if(!p.sessions)throw 0;plan=p;A={};state.week=1;save();state.screen='plan';render()}catch{alert('Use a BUILD plan JSON file.')}});render();